### ISSUE TITLE
Latitude is not properly converted to degrees from NMEA message

### ISSUE THREAD

**Issue by MathiasVDA** [GhostwareDev/NMEAParser#7]
The NMEA message

$GPRMC,153007,A,5050.10288,N,00419.91808,E,000.1,078.9,100217,,,A*75

return a latitude of 6.xxx° while it should be 4.xxx°

I've created a fork on which I'll fix the conversion

**Comment by kevingoos** [comment]
Thx for your fix, I will put the fix in the next release!
